### ISSUE TITLE
Cast Exception

### ISSUE THREAD

**Issue by caipivara** [raniejade/spek-idea-plugin#27]
- Android studio `2.2.3`
- Kotlin `1.0.6`
- Spek idea plugin  `0.3.2`

Im getting 

```
org.jetbrains.spek.idea.SpekConfigurationFactory@6d32e6e produced wrong type: org.jetbrains.kotlin.psi.KtBlockExpression cannot be cast to org.jetbrains.kotlin.psi.KtLambdaExpression
java.lang.ClassCastException: org.jetbrains.kotlin.psi.KtBlockExpression cannot be cast to org.jetbrains.kotlin.psi.KtLambdaExpression
	at org.jetbrains.spek.idea.SpekUtils.getLambaExpression(SpekUtils.kt:141)
	at org.jetbrains.spek.idea.SpekUtils.extractPath(SpekUtils.kt:108)
	at org.jetbrains.spek.idea.SpekUtils.extractPath(SpekUtils.kt:129)
	at org.jetbrains.spek.idea.SpekUtils.extractPath$default(SpekUtils.kt:107)
	at org.jetbrains.spek.idea.SpekRunConfigurationProducer.setupConfigurationFromContext(SpekRunConfigurationProducer.kt:78)
	at org.jetbrains.spek.idea.SpekRunConfigurationProducer.setupConfigurationFromContext(SpekRunConfigurationProducer.kt:22)
	at com.intellij.execution.actions.RunConfigurationProducer.createLightConfiguration(RunConfigurationProducer.java:251)
	at com.intellij.execution.lineMarker.ExecutorAction.createConfiguration(ExecutorAction.java:96)
	at com.intellij.execution.lineMarker.ExecutorAction.access$100(ExecutorAction.java:39)
	at com.intellij.execution.lineMarker.ExecutorAction$2.fun(ExecutorAction.java:83)
	at com.intellij.execution.lineMarker.ExecutorAction$2.fun(ExecutorAction.java:80)
	at com.intellij.util.containers.ContainerUtil.mapNotNull(ContainerUtil.java:1889)
	at com.intellij.execution.lineMarker.ExecutorAction.getActionName(ExecutorAction.java:79)
	at com.intellij.execution.lineMarker.ExecutorAction.update(ExecutorAction.java:65)
	at com.intellij.execution.lineMarker.LineMarkerActionWrapper.update(LineMarkerActionWrapper.java:46)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.isAvailable(GutterIntentionAction.java:71)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.addActions(GutterIntentionAction.java:137)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.addActions(GutterIntentionAction.java:130)
	at com.intellij.codeInsight.daemon.impl.GutterIntentionAction.addActions(GutterIntentionAction.java:98)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:330)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:201)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1181)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by raniejade** [comment]
Can you provide the class the editor is at when that exception happened? That would help speed up replication :)
