### ISSUE TITLE
AbstractMethodError when running test from IntelliJ

### ISSUE THREAD

**Issue by xgouchet** [raniejade/spek-idea-plugin#40]
I'm getting an `AbstractMethodError` whenever I try to run a test using the icons in the gutter : 

```
Testing started at 20:01 ...
Jun 01, 2017 8:01:22 PM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [spek]
Exception in thread "main" java.lang.AbstractMethodError: Method org/jetbrains/spek/engine/Scope$Group.isTest()Z is abstract
	at org.jetbrains.spek.engine.Scope$Group.isTest(Scope.kt)
	at org.junit.platform.engine.TestDescriptor.hasTests(TestDescriptor.java:160)
	at org.junit.platform.launcher.core.Root.lambda$static$0(Root.java:33)
	at org.junit.platform.engine.TestDescriptor.accept(TestDescriptor.java:179)
	at org.junit.platform.engine.TestDescriptor.lambda$accept$0(TestDescriptor.java:181)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.junit.platform.engine.TestDescriptor.accept(TestDescriptor.java:181)
	at org.junit.platform.launcher.core.Root.lambda$acceptInAllTestEngines$2(Root.java:85)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at org.junit.platform.launcher.core.Root.acceptInAllTestEngines(Root.java:85)
	at org.junit.platform.launcher.core.Root.prune(Root.java:77)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
```

The tests run without error when running the `junitPlatformTest` from gradle. 

I'm using : 
 - IntelliJ `2017.1.3`
 - Spek Plugin `0.3.4`
 - Spek library `1.1.2`
 - JUnit Platform Gradle plugin `1.0.0-M4`
 - Kotlin version `1.1.2-4`

Let me know if you need more information on this issue

**Comment by xgouchet** [comment]
I found that this was a duplicate of #37 : adding `testRuntime "org.junit.platform:junit-platform-launcher:1.0.0-M4"` solved this issue for me.
