### ISSUE TITLE
Could not load test class on Kotlin 1.2-M2 or 1.2.0-beta-31

### ISSUE THREAD

**Issue by bazted** [raniejade/spek-idea-plugin#50]
I am using Android Studio 3.0 beta 6.

It is a project which has android.application module & JVM module(Kotlin). 
Kotlin module contains all tests written on Spek. 

I was creating the project at the time of release 1.2-M1, and used 
` 
           spek        : '1.1.2',
            junit_platform  : '1.0.0-M4',
            junit_jupiter : '5.0.0-M4'
`
Yesterday I have upgraded dependencies above to 
`
            spek        : '1.1.5',
            junit_platform  : '1.0.0',
            junit_jupiter : '5.0.0'
`
Everything worked fine.  `gradlew test` runs & passes all tests and the most important I could run tests from AS using Spek plugin 0.4.3. 

But if I upgrade Kotlin version to 1.2-M2 or 1.2.0-beta-31  - `gradlew test` works as expected, but plugin throws: 

```
         Oct 04, 2017 8:32:09 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
         WARNING: TestEngine with ID 'spek' failed to discover tests
         org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: com.b.b.b.AppInteractorTest
	at 
     org.junit.platform.engine.discovery.ClassSelector.lambda$getJavaClass$0(ClassSelector.java:71)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:70)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:79)
	at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:50)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
```

Firstly, I though it is connected with https://github.com/spekframework/spek/issues/181 , but in this case running `compileTestJava` does not help.

**Comment by raniejade** [comment]
Can you check this out https://github.com/spekframework/spek/blob/e659eb633928f74cc52480e734ab6155dc310656/documentation/src/asciidoc/setting-up.adoc#setting-up-android?

**Comment by bazted** [comment]
It is about configuring Android module, while mine Android module is without tests for now. 
Copying src's can make the trick, but the configuration in documentations is heavily dependent on Androids variants. 

Additionally, there is process command listed by AS. 
``` 
Process finished with exit code 0

"/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/bin/java" "-javaagent:/Applications/Android Studio 3.0 Preview.app/Contents/lib/idea_rt.jar=61356:/Applications/Android Studio 3.0 Preview.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/charsets.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/ext/localedata.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/ext/sunec.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/jce.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/jsse.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/management-agent.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/resources.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/jre/lib/rt.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/lib/dt.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/lib/jconsole.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/lib/sa-jdi.jar:/Applications/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/lib/tools.jar:/Users/b/projects/android-app/app-bl/build/classes/java/main:/Users/b/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.2.0-beta-31/6ae31b35cf43e9f681be0aa12c1f3799c29e167f/kotlin-reflect-1.2.0-beta-31.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.0-beta-31/aaf06727bfa71cc521be671d2642ffd75f32e8aa/kotlin-stdlib-1.2.0-beta-31.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-android/0.17/4cb65eee9fa19c3c9bcf8cab0615ac78f401aad2/kotlinx-coroutines-android-0.17.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-rx2/0.17/d1c73587e92020dd8be1a80e090a13623e64a44/kotlinx-coroutines-rx2-0.17.jar:/Users/b/.gradle/caches/modules-2/files-2.1/ru.gildor.coroutines/kotlin-coroutines-retrofit/0.7.1/e6a9e254c48b2dcd330b05513a3f5b68de2e4ba9/kotlin-coroutines-retrofit-0.7.1.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-reactive/0.17/f69218cb666eec296274c1ffd4205bc386073ab6/kotlinx-coroutines-reactive-0.17.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-coroutines-core/0.17/1523b41cc0bb0add072b28b1d2a47394e289fc7/kotlinx-coroutines-core-0.17.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.workhq.erp/data/1.0.9.37/a9663b1c56495c429a0f80075aee4aea5beaa7df/data-1.0.9.37.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/logging-interceptor/3.8.1/feab46062803513d6a8307c74b0084265855de1a/logging-interceptor-3.8.1.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.github.salomonbrys.kodein/kodein/4.0.0/ad93abe754f10641d9d942cab0f86aea76a54b59/kodein-4.0.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.hannesdorfmann.mosby3/mvi-common/3.0.4/e918a77ccae672606d1cd7ce55f0b96cce9d7938/mvi-common-3.0.4.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.hannesdorfmann.mosby3/mvp-common/3.0.4/d1453001eb316595a11ed72673f189c05d27914d/mvp-common-3.0.4.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.android.support/support-annotations/26.1.0/814258103cf26a15fcc26ecce35f5b7d24b73f8/support-annotations-26.1.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/converter-gson/2.3.0/9e09011e9767bb76b5e27c9b8223476b93b14631/converter-gson-2.3.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit/2.3.0/bcacde6a8ccedcc56c127403d26b76072fe6214d/retrofit-2.3.0.jar:/Applications/Android Studio 3.0 Preview.app/Contents/gradle/m2repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/io.reactivex.rxjava2/rxjava/2.1.4/6a31162e65fba325430d9b9fec6b6e6ba31ee832/rxjava-2.1.4.jar:/Users/b/.gradle/caches/modules-2/files-2.1/io.requery/requery-kotlin/1.4.0/183920faa4c1f1f9e339200bdcbc55a6b1032a17/requery-kotlin-1.4.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.2/3edcfe49d2c6053a70a2a47e4e1c2f94998a49cf/gson-2.8.2.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/3.8.1/4d060ca3190df0eda4dc13415532a12e15ca5f11/okhttp-3.8.1.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.github.salomonbrys.kodein/kodein-core/4.0.0/628649b390ddb920c2790efc3c041e730dbfa75e/kodein-core-4.0.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.reactivestreams/reactive-streams/1.0.1/1b1c911686eb40179219466e6a59b634b9d7a748/reactive-streams-1.0.1.jar:/Users/b/.gradle/caches/modules-2/files-2.1/io.requery/requery/1.4.0/7bc82d3637ea74ee67d80044a068a4f2e11eb35e/requery-1.4.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.squareup.okio/okio/1.13.0/a9283170b7305c8d92d25aff02a6ab7e45d06cbe/okio-1.13.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.squareup.retrofit2/retrofit-mock/2.3.0/d6a3f36b8ec9e23d467a0deb6e2d253195e05cd7/retrofit-mock-2.3.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/junit/junit/4.12/2973d150c0dc1fefe998f834810d68f278ea58ec/junit-4.12.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/mockwebserver/3.8.1/5006fc4cf446073ecc166ecac6543659dab298ed/mockwebserver-3.8.1.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-inline/2.8.47/8361e273c77429300d702617fa288edb20223b09/mockito-inline-2.8.47.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.nhaarman/mockito-kotlin-kt1.1/1.5.0/3cb5419929540bcb25bdcc5e9ff7c8a1cb5831c/mockito-kotlin-kt1.1-1.5.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/com.nhaarman/mockito-kotlin/1.5.0/25faa884f76375f76cdbd6651c4cebcde36d4117/mockito-kotlin-1.5.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/2.8.47/48840cfced22ec0c07203a0201c5ae7bc12557b5/mockito-core-2.8.47.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.jetbrains.spek/spek-api/1.1.5/bc19a88a54bb18edc9dd64d79b42f32b3215f1ca/spek-api-1.1.5.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-console/1.0.0/2931079616796bc4537f7e3c236f8fdfe7e51237/junit-platform-console-1.0.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.0.0/f7fe1b74bef74d640493781abecafba191472ad/junit-jupiter-api-5.0.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.hamcrest/hamcrest-core/1.3/42a25dc3219429f0e5d060061f71acb49bf010a0/hamcrest-core-1.3.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.50/be504b4901d75cbe129a178f5830e6c358ec214c/bcprov-jdk15on-1.50.jar:/Users/b/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy/1.6.14/871c3e49dc6183d0d361601c2f1d11abb1a6b48c/byte-buddy-1.6.14.jar:/Users/b/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.6.14/ba1e5ba3a84fb2fbf2f4de9138df19665eec4d59/byte-buddy-agent-1.6.14.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.objenesis/objenesis/2.5/612ecb799912ccf77cba9b3ed8c813da086076e9/objenesis-2.5.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-launcher/1.0.0/5602a195a442636276efefce2a4c7b418cd67e5c/junit-platform-launcher-1.0.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-engine/1.0.0/fdc6f63a689b894529ea5e9e218b65422748fd/junit-platform-engine-1.0.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.0.0/d2e03d9b21020746d48fe45834ff7d71fbcbd7b2/junit-platform-commons-1.0.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.apiguardian/apiguardian-api/1.0.0/3ef5276905e36f4d8055fe3cb0bdcc7503ffc85d/apiguardian-api-1.0.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.0.0/6f09c598e9ff64bf0ce2fa7e7de49a99ba83c0b4/opentest4j-1.0.0.jar:/Users/b/.gradle/caches/modules-2/files-2.1/org.jetbrains.spek/spek-junit-platform-engine/1.1.5/84bbc6c2b61230b5921458b87332672d08fdc1e3/spek-junit-platform-engine-1.1.5.jar:/Users/b/Library/Application Support/AndroidStudioPreview3.0/spek-idea-plugin/lib/tooling-0.4.3.jar" org.jetbrains.spek.tooling.MainKt --spec com.b.b.b.BackstackTest 
```
It contains pretty strange path. `/Users/b/projects/android-app/app-bl/build/classes/java/main` which leads firstly to JAVA not Kotlin src directory, secondly to `main` srcSet instead of `test`.

Just to make sure mine `app-bl` module is not an Android one. It is pure Kotlin 

```
apply plugin: 'kotlin'
apply plugin: 'idea'
apply plugin: 'org.junit.platform.gradle.plugin'
```

**Comment by raniejade** [comment]
This should be fixed in the latest plugin version.

**Comment by bazted** [comment]
Thank you very much.
